import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navBar/navBar";
import Footer from "../components/footer/footer";
import {ThemeProvider} from "@/context/ThemeContext"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider> {/* 👈 wrap here */}
          <div className="wrapper">
            <div className="container">
              <NavBar />
              {children}
              <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}